name: CyberDrive
options:
  minimumXcodeGenVersion: 2.42.0
  deploymentTarget:
    iOS: "18.4"
packages:
  MapLibre:
    url: https://github.com/maplibre/maplibre-gl-native-distribution
    from: 6.28.0
targets:
  CyberDrive:
    type: application
    platform: iOS
    sources:
      - path: CyberDrive
    resources:
      - path: CyberDrive/Resources
      - path: CyberDrive/Assets.xcassets
    dependencies:
      - package: MapLibre
        product: MapLibre
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ajxlf.CyberDrive
        PRODUCT_NAME: CyberDrive
        EXECUTABLE_NAME: CyberDrive
        SWIFT_VERSION: "5.10"
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: CyberDrive/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: CyberDrive/Resources/CyberDrive.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: YES
        SUPPORTS_MACCATALYST: NO
        UI_USER_INTERFACE_IDIOM: phone
        LSRequiresIPhoneOS: YES
        GENERATE_INFOPLIST_FILE: NO
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
    scheme:
      gatherCoverageData: false
      testTargets: []
